apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yeq48f3op-python
  janus-idp.io/tekton: yeq48f3op-python
  backstage.io/kubernetes-id: yeq48f3op-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yeq48f3op-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
