apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yeq48f3op-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yeq48f3op-python 
  name: yeq48f3op-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yeq48f3op-python 
